SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS project24 DEFAULT CHARACTER SET utf8 ;
USE project24 ;

CREATE TABLE IF NOT EXISTS project24.user (
  uid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(20) NOT NULL UNIQUE,
  firstname VARCHAR(45) NOT NULL DEFAULT "John",
  lastname VARCHAR(45) NOT NULL DEFAULT "Doe",
  password VARCHAR(60) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  country VARCHAR(45) NOT NULL,
  city VARCHAR(45) NOT NULL
  ) ENGINE = InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS project24.hobby (
  hid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(45) NOT NULL UNIQUE
  ) ENGINE = InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS project24.hobbyuser (
  user_id INT NOT NULL,
  hobby_id INT NOT NULL,
  CONSTRAINT uid 
		FOREIGN KEY (user_id) 
        REFERENCES project24.user(uid)
        ON DELETE CASCADE,
  CONSTRAINT hid 
		FOREIGN KEY (hobby_id) 
        REFERENCES project24.hobby(hid)
        ON DELETE CASCADE
  ) ENGINE = InnoDB DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;