spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project24
    username: root
    password: password
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 5000

security:
  basic:
    enabled: false
  jwt:
    token:
      secret-key: yqwSgpaSDnAmaLH
      expire-length: 3600000 # 60 minutes * 60 seconds * 1000 miliseconds
