spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project24?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 5000

security:
  basic:
    enabled: false
  jwt:
    token:
      secret-key: not-so-secret-key
      expire-length: 1800000 # 30 minutes * 60 seconds * 1000 miliseconds
